### ISSUE TITLE
logalloc_test.cc(1531): fatal error: in "background_reclaim": critical check compacted_pre == compacted_post has failed [1003020157 != 1004194057]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#8234]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/3268/artifact/testlog/release/logalloc_test.240.log
Scylla version 2d9feaacea4673389f98f0525a4137eb382abff9
```
random-seed=182225916
...
compacted 1004194057 items 2403977 (post)
test/boost/logalloc_test.cc(1531): fatal error: in "background_reclaim": critical check compacted_pre == compacted_post has failed [1003020157 != 1004194057]
```

**Comment by bhalevy** [comment]
@avikivity can you please look into this?

**Comment by avikivity** [comment]
This is test flakiness, the test depends on runtime performance. I'll look at a way to make it more reliable.

**Comment by nyh** [comment]
Reproduced again in https://jenkins.scylladb.com/job/scylla-master/job/next/3292//consoleText

**Comment by avikivity** [comment]
Introduced in ecb6c56a2acb93537d166c35cf534db98e9d12a1, not in any release stream, so no backport needed.

**Comment by bhalevy** [comment]
Reproduced in a branch off of 5.1.dev ea3da23f3b
Not reproducible with same random seed.

[logalloc_test.39.log](https://github.com/scylladb/scylla/files/9053284/logalloc_test.39.log)

**Comment by bhalevy** [comment]
reproduced randomly, once in a 1000 times that I tried.

**Comment by bhalevy** [comment]
Seen now also in https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/next/588/artifact/testlog/x86_64_dev/logalloc_test.242.log

**Comment by bhalevy** [comment]
Cc @tgrabiec any idea what could have caused it to happen more frequently recently?

**Comment by bhalevy** [comment]
Could this be related to ff2cd72766ccc96d8d1d319f6bf9445beb20b5d7?

**Comment by avikivity** [comment]
Which subtest fails?

**Comment by bhalevy** [comment]
> Which subtest fails?

background_reclaim, in https://github.com/scylladb/scylla/blob/5a30f9b7894abbeb196d179294f9320cc53534ba/test/boost/logalloc_test.cc#L1523

**Comment by bhalevy** [comment]
In https://github.com/scylladb/scylla/issues/8851 the theory is that the failure is timing related and the test fails when the host is heavily loaded.

I'm not sure if this explains the higher probability of this test to in 2021.1 next promotion.  See https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/next/594/testReport/test_boost_logalloc_test.cc/test_boost_logalloc_test/background_reclaim/history/

If so, maybe we need to disable it until this is sorted out.

**Comment by bhalevy** [comment]
@avikivity / @tgrabiec assuming the test cannot accurately synchronize with background reclaim, is the following correct?
```diff
diff --git a/test/boost/logalloc_test.cc b/test/boost/logalloc_test.cc
index 8461c05599..963b30e067 100644
--- a/test/boost/logalloc_test.cc
+++ b/test/boost/logalloc_test.cc
@@ -1520,7 +1520,7 @@ SEASTAR_THREAD_TEST_CASE(background_reclaim) {
         std_allocs.emplace_back(managed_bytes::initialized_later(), std_alloc_size);
         auto compacted_post = logalloc::memory_compacted();
         fmt::print("compacted {} items {} (post)\n", compacted_post, evictable_allocs.size());
-        BOOST_REQUIRE_EQUAL(compacted_pre, compacted_post);
+        BOOST_REQUIRE_LE(compacted_pre, compacted_post);
     
         // Pretend to do some work. Sleeping would be too easy, as the background reclaim group would use
         // all that time.
```

**Comment by avikivity** [comment]
This will allow the test to pass even if background reclaim doesn't work.

I guess we could/should white-box it by looking at metrics (or some other signal) so see that background_reclaim did have a chance to run.

**Comment by avikivity** [comment]
It would transform failures into hangs, but that's better than false positives.

**Comment by bhalevy** [comment]
@avikivity unfortunately the test keeps failing in next-2021.1 even with the hardening patch

**Comment by avikivity** [comment]
Easily reproduces with high --repeat/

**Comment by avikivity** [comment]
Not so in master. So there's an extra fix somewhere.

**Comment by bhalevy** [comment]
next-2021.1 looks much better since https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/next/633/ 2741e81c28a7a446614d9331d3e6bdd285121516

**Comment by bhalevy** [comment]
Stumbled upon this locally (not reproducible with same seed):
```
=== TEST.PY STARTING TEST boost.logalloc_test.1 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/home/bhalevy/dev/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
build/dev/test/boost/logalloc_test --report_level=no --logger=HRF,test_suite:XML,test_suite,/home/bhalevy/dev/scylla/testlog/dev/xml/boost.logalloc_test.1.xunit.xml --catch_system_errors=no --color_output=false -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
=== TEST.PY TEST boost.logalloc_test.1 OUTPUT ===
Running 18 test cases...
Entering test module "Master Test Suite"
test/boost/logalloc_test.cc(50): Entering test case "test_prime_logalloc"
INFO  2023-04-04 14:43:18,411 seastar - Reactor backend: linux-aio
WARN  2023-04-04 14:43:18,412 [shard 0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
INFO  2023-04-04 14:43:18,413 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-04-04 14:43:18,413 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-04-04 14:43:18,413 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-04-04 14:43:18,413 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-04-04 14:43:18,416 [shard 1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:13, perf_event_open() failed: Permission denied)
random-seed=581778152
test/boost/logalloc_test.cc(50): Leaving test case "test_prime_logalloc"; testing time: 135023us
test/boost/logalloc_test.cc(54): Entering test case "test_compaction"
test/boost/logalloc_test.cc(54): Leaving test case "test_compaction"; testing time: 13798us
test/boost/logalloc_test.cc(99): Entering test case "test_occupancy"
test/boost/logalloc_test.cc(99): Leaving test case "test_occupancy"; testing time: 155us
test/boost/logalloc_test.cc(133): Entering test case "test_compaction_with_multiple_regions"
test/boost/logalloc_test.cc(133): Leaving test case "test_compaction_with_multiple_regions"; testing time: 29439us
test/boost/logalloc_test.cc(204): Entering test case "test_mixed_type_compaction"
test/boost/logalloc_test.cc(204): Leaving test case "test_mixed_type_compaction"; testing time: 237us
test/boost/logalloc_test.cc(295): Entering test case "test_blob"
test/boost/logalloc_test.cc(295): Leaving test case "test_blob"; testing time: 122us
test/boost/logalloc_test.cc(311): Entering test case "test_merging"
test/boost/logalloc_test.cc(311): Leaving test case "test_merging"; testing time: 317us
test/boost/logalloc_test.cc(346): Entering test case "test_region_move"
test/boost/logalloc_test.cc(346): Leaving test case "test_region_move"; testing time: 103us
test/boost/logalloc_test.cc(359): Entering test case "test_region_lock"
test/boost/logalloc_test.cc(359): Leaving test case "test_region_lock"; testing time: 925us
test/boost/logalloc_test.cc(416): Entering test case "test_large_allocation"
test/boost/logalloc_test.cc(416): Leaving test case "test_large_allocation"; testing time: 338414us
test/boost/logalloc_test.cc(487): Entering test case "test_zone_reclaiming_preserves_free_size"
INFO  2023-04-04 14:43:18,808 [shard 0] testlog - non_lsa_used_space = 24076288
INFO  2023-04-04 14:43:18,808 [shard 0] testlog - region_occupancy = 99.14%, 75497579 / 76152832 [B]
INFO  2023-04-04 14:43:18,811 [shard 0] testlog - non_lsa_used_space = 22831104
INFO  2023-04-04 14:43:18,811 [shard 0] testlog - region_occupancy = 66.43%, 261201 / 393216 [B]
INFO  2023-04-04 14:43:18,811 [shard 0] testlog - non_lsa_used_space = 22831104
INFO  2023-04-04 14:43:18,811 [shard 0] testlog - region_occupancy = 66.43%, 261201 / 393216 [B]
test/boost/logalloc_test.cc(487): Leaving test case "test_zone_reclaiming_preserves_free_size"; testing time: 9036us
test/boost/logalloc_test.cc(525): Entering test case "test_can_reclaim_contiguous_memory_with_mixed_allocations"
test/boost/logalloc_test.cc(525): Leaving test case "test_can_reclaim_contiguous_memory_with_mixed_allocations"; testing time: 189118us
test/boost/logalloc_test.cc(593): Entering test case "test_decay_reserves"
test/boost/logalloc_test.cc(593): Leaving test case "test_decay_reserves"; testing time: 140655us
test/boost/logalloc_test.cc(688): Entering test case "background_reclaim"
compacted 2672739294 items 2413090 (pre)
compacted 2672739294 items 2413090 (post)
compacted 2677113469 items 2410320 (pre)
compacted 2677113469 items 2410320 (post)
compacted 2680857144 items 2407841 (pre)
compacted 2680857144 items 2407841 (post)
compacted 2685797794 items 2404992 (pre)
compacted 2685797794 items 2404992 (post)
compacted 2689354594 items 2402495 (pre)
compacted 2689354594 items 2402495 (post)
compacted 2695892619 items 2399655 (pre)
compacted 2695892619 items 2399655 (post)
compacted 2699850469 items 2396969 (pre)
compacted 2699850469 items 2396969 (post)
compacted 2705697219 items 2393692 (pre)
compacted 2705697219 items 2393692 (post)
compacted 2708463294 items 2392316 (pre)
compacted 2708463294 items 2392316 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2714505694 items 2388827 (post)
compacted 2714505694 items 2388827 (pre)
compacted 2718983544 items 2386406 (post)
test/boost/logalloc_test.cc(757): fatal error: in "background_reclaim": critical check compacted_pre == compacted_post has failed [2714505694 != 2718983544]
test/boost/logalloc_test.cc(688): Leaving test case "background_reclaim"; testing time: 6370765us
test/boost/logalloc_test.cc(782): Entering test case "test_buf_allocation"
test/boost/logalloc_test.cc(782): Leaving test case "test_buf_allocation"; testing time: 374us
test/boost/logalloc_test.cc(843): Entering test case "test_lsa_buffer_alloc_dealloc_patterns"
test/boost/logalloc_test.cc(843): Leaving test case "test_lsa_buffer_alloc_dealloc_patterns"; testing time: 4319us
test/boost/logalloc_test.cc(1045): Entering test case "test_weak_ptr"
test/boost/logalloc_test.cc(1045): Leaving test case "test_weak_ptr"; testing time: 220us
test/boost/logalloc_test.cc(1112): Entering test case "test_buf_alloc_compaction"
test/boost/logalloc_test.cc(1112): Leaving test case "test_buf_alloc_compaction"; testing time: 12633us
Leaving test module "Master Test Suite"; testing time: 7246204us
=== TEST.PY SUMMARY START ===
Test exited with code 201

=== TEST.PY SUMMARY END ===
```

**Comment by avikivity** [comment]
Reproduced with: `./test.py --mode release logalloc_test --repeat 4000 --jobs 100` (on a 1s16c32t machine)

**Comment by avikivity** [comment]
More reliable reproducer: `nice ./test.py --mode release logalloc_test --repeat 4000 --jobs 120`. This pushes my 128GB machine slightly into swap.

**Comment by tchaikov** [comment]
despite that this issue was opened before #15677, i am closing this issue as a dup of the latter. because  #15677 includes more analysis.
