### ISSUE TITLE
ScyallDB doesn't compile with boost versions >= 1.79.0

### ISSUE THREAD

**Issue by lkshminarayanan** [scylladb/scylladb#16746]
ScyllaDB compilation fails with the following error when compiled with boost versions >= 1.79.0

```
/temp/scylladb/types/types.cc:2581:16: error: no matching function for call to 'align_up'
        return align_up(boost::multiprecision::msb(num) + 2, 8u) / 8;
               ^~~~~~~~
/temp/scylladb/seastar/include/seastar/core/align.hh:36:3: note: candidate template ignored: deduced conflicting types for parameter 'T' ('typename std::enable_if<number_category<cpp_int_backend<0, 0, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, allocator<unsigned long long>>>::value == number_kind_integer, std::size_t>::type' (aka 'unsigned long') vs. 'unsigned int')
T align_up(T v, T align) {
  ^
/temp/scylladb/seastar/include/seastar/core/align.hh:42:4: note: candidate template ignored: could not match 'T *' against 'typename std::enable_if<number_category<cpp_int_backend<0, 0, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, allocator<unsigned long long>>>::value == number_kind_integer, std::size_t>::type' (aka 'unsigned long')
T* align_up(T* v, size_t align) {
   ^
1 error generated.
ninja: build stopped: subcommand failed.

```

**Comment by lkshminarayanan** [comment]
> you meant to say boost 1.80.0 ? i think the problem manifests itself with boost 1.79.0 and up. see https://godbolt.org/z/n61qbKs5o

My bad. I probably missed it while testing with different boost versions back and forth. I'll update the PR and commit with the correct version.
