### PR TITLE
test/boost/sstable_datafile_test : don't require page-granular growth in the small sstable memory test

### LINKED ISSUE #31199: test_small_sstable_has_reasonable_memory_usage fails when other test cases ran first in the same process
`test_small_sstable_has_reasonable_memory_usage` fails whenever it is not the first thing the process does.

### Reproduction

```
$ ./build/dev/test/boost/sstable_datafile_test -- -c1 -m2G
test/boost/sstable_datafile_test.cc(3552): fatal error in "test_small_sstable_has_reasonable_memory_usage":
    critical check growth >= lower_bound has failed [0 < 11584]
INFO  testlog - live-memory growth from holding 8 dict-compressed sstables: 0 bytes
    (lower_bound: 11584 bytes, upper_bound: 262144 bytes, dict_size: 112640 bytes)
```

Deterministic, dev mode. The same case passes on its own:

```
$ ./build/dev/test/boost/sstable_datafile_test --run_test=test_small_sstable_has_reasonable_memory_usage -- -c1 -m2G
live-memory growth ...: 184320 bytes
*** No errors detected
```

Nothing in between is needed - five preceding cases already halve the measured growth:

```
$ ./build/dev/test/boost/sstable_datafile_test \
    --run_test='datafile_generation_09,datafile_generation_11,datafile_generation_12,test_counter_write,check_read_indexes,test_small_sstable_has_reasonable_memory_usage' \
    -- -c1 -m2G
live-memory growth ...: 73728 bytes
```

CI is unaffected, which is why this has gone unnoticed: `test/pylib/cpp/boost.py` passes
`--run_test=<case>` and runs one process per case, unless the suite is listed in
`no_parallel_cases` - `sstable_datafile_test` is not. So the case only fails when a developer
runs the binary directly, or if the suite is ever moved to `no_parallel_cases`. It reproduces
on master and predates the branch I found it on.

### Cause

`test/boost/sstable_datafile_test.cc:3552` asserts a lower bound on the measurement:

```cpp
    const size_t lower_bound = num_sstables * sizeof(sstable);
    ...
    BOOST_REQUIRE_GE(growth, lower_bound);
```

`memory::stats().allocated_memory()` is `_total_memory - _free_memory`, i.e.
`(cpu_mem.nr_pages - cpu_mem.nr_free_pages) * page_size` (`seastar/src/core/memory.cc:1958`).
It is the memory the allocator holds *in pages*, not the live bytes. `small_pool` keeps up to
`_max_free = max(100, span_bytes * 2 / object_size)` free objects and only trims down to
`(_min_free + _max_free) / 2` (`memory.cc:1437`, `:1525`), so once a pool is warm it permanently
holds the pages behind ~50-100 free objects. In a process that has already run a few hundred
cases, every small allocation the measured batch makes is served from a pool free list and the
page-level occupancy does not move at all - hence exactly 0. So the assertion is not an
invariant of the thing being measured.

Two smaller problems in the same block:

* `auto growth = allocated_after - allocated_before;` is unsigned. `allocated_memory()` can
  legitimately *decrease* across the batch, when the write path's churn makes a pool trim its
  free list and hand spans back; that underflows into a huge positive number and fails the
  upper bound instead.
* The single-sstable warm-up leaves the pools cold, so the measured growth in a fresh process
  (184320) sits at 70% of the 262144 upper bound - one pool taking a fresh span is enough to
  push it over.

### Fix

Drop the lower bound; the upper bound does not need it. A per-sstable copy of the dictionary is
far too large for a small pool, so it can only come from free pages, and 8 live copies cannot
hide under `8 * 32 KiB`. Verified by reverting the one line the test was written for
(`_sst._components->compression.discard_hidden_options()`, 691f20b40e): the test still fails in
both modes, at 1093632 (standalone) / 1081344 (whole binary) bytes against the 262144 bound.

Also compute the growth signed, and warm up with a full batch instead of one sstable, which
brings the cold-process measurement down to 45056 bytes - well clear of the bound rather than at
70% of it.

cc @michoecho (author of 691f20b40e, which added the test)

### PR DESCRIPTION
**Pull request by mykaul**
`test_small_sstable_has_reasonable_memory_usage` fails deterministically whenever it is not the first thing the process does:

```
$ ./build/dev/test/boost/sstable_datafile_test -- -c1 -m2G
test/boost/sstable_datafile_test.cc(3552): fatal error in "test_small_sstable_has_reasonable_memory_usage":
    critical check growth >= lower_bound has failed [0 < 11584]
INFO  testlog - live-memory growth from holding 8 dict-compressed sstables: 0 bytes
    (lower_bound: 11584 bytes, upper_bound: 262144 bytes, dict_size: 112640 bytes)
```

| how it is run | measured growth | result |
|---|---|---|
| `--run_test=test_small_sstable_has_reasonable_memory_usage` | 184320 | pass |
| after 5 preceding cases | 73728 | pass |
| whole binary | 0 | **fail** |

The lower bound, `growth >= num_sstables * sizeof(sstable)`, is not an invariant of what it measures. `memory::stats().allocated_memory()` is `(nr_pages - nr_free_pages) * page_size`
- memory the allocator holds **in pages**, not live bytes. A `small_pool` retains up to `_max_free = max(100, span_bytes*2/object_size)` free objects and trims only down to
`(_min_free+_max_free)/2` (`seastar/src/core/memory.cc:1437`, `:1525`), so once warm it keeps those pages for good. In a process that has already run a few hundred cases, the whole
measured batch is served from pool free lists and page occupancy does not move at all.

CI has never hit this: `test/pylib/cpp/boost.py` passes `--run_test=<case>` and forks one process per case unless the suite is in `no_parallel_cases`, which `sstable_datafile_test` is not.
It only shows up when the binary is run directly.

The upper bound is the guard that matters, and it does not need the lower one - a per-sstable copy of the dictionary is far too large for a small pool, so it can only come from free pages,
and 8 live copies cannot hide inside `8 * 32 KiB`. Verified by reverting the fix this test was written for (`691f20b40e`, `compression.discard_hidden_options()`): it then fails in **both**
modes, at 1093632 / 1081344 bytes against the 262144 bound.

Two adjacent fragilities fixed while here:

- `growth` was computed in `size_t`. `allocated_memory()` can legitimately **drop** across the batch, when the write path's churn makes a pool trim its free list and hand spans back - that
  underflowed to a huge positive number and failed the *upper* bound. Compute it signed.
- Warm up with a full batch rather than a single sstable, so the pools are in the steady state the measured batch will find them in. Cold-process growth drops from 184320 to 45056 bytes,
  well clear of the bound instead of sitting at 70% of it.

Test-only change. Built and run under `dbuild`, dev mode, `-c1 -m2G`: passes both standalone and as part of the full `sstable_datafile_test` binary.

Fixes: SCYLLADB-3875
Fixes: #31199

Backport: no, edge case in testing.

### CODE REVIEW

**Comment by mykaul** [comment]
@denesb - can someone from the team review it? For some reason, I keep failing on this.

**Review by denesb — APPROVED** [review]
