### ISSUE TITLE
`make -C docs multiversion` fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#12704]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

```
make -C docs multiversion
...
No dependencies to install or update
[71](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:72)
poetry run sphinx-multiversion . _build/dirhtml -D html_theme_options.collapse_navigation='false' -D html_theme_options.navigation_depth=3
[72](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:73)
Traceback (most recent call last):
[73](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:74)
  File "/home/runner/.cache/pypoetry/virtualenvs/scylla-l02JF1V7-py3.7/bin/sphinx-multiversion", line 8, in <module>
[74](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:75)
    sys.exit(main())
[75](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:76)
  File "/home/runner/.cache/pypoetry/virtualenvs/scylla-l02JF1V7-py3.7/lib/python3.7/site-packages/sphinx_multiversion/main.py", line 215, in main
[76](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:77)
    confdir_absolute, confoverrides, add_defaults=True
[77](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:78)
  File "/home/runner/.cache/pypoetry/virtualenvs/scylla-l02JF1V7-py3.7/lib/python3.7/site-packages/sphinx_multiversion/main.py", line 93, in load_sphinx_config
[78](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:79)
    raise result
[79](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:80)
sphinx.errors.ConfigError: There is a programmable error in your configuration file:
[80](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:81)

[81](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:82)
Traceback (most recent call last):
[82](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:83)
  File "/home/runner/.cache/pypoetry/virtualenvs/scylla-l02JF1V7-py3.7/lib/python3.7/site-packages/sphinx/config.py", line 329, in eval_config_file
[83](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:84)
    exec(code, namespace)
[84](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:85)
  File "/home/runner/work/scylladb/scylladb/docs/conf.py", line 69, in <module>
[85](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:86)
    tags.add(flag)
[86](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:87)
AttributeError: 'NoneType' object has no attribute 'add'
[87](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:88)

[88](https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952#step:5:89)
make: *** [Makefile:72: multiversion] Error 1
```

see https://github.com/scylladb/scylladb/actions/runs/4069477061/jobs/7009261952

this is a regression introduced by 616bf26422996d5b722eb8d25df27a20828d0eb9. and should be fixed once

1. https://github.com/dgarcia360/sphinx-multiversion/pull/4 gets merged
2. sphinx-multiversion-scylla is tagged with a new release
3. the new release of sphinx-multiversion-scylla is published to pypi
4. the version of `sphinx-multiversion-scylla` is bumped in `docs/pyproject.toml` 

@dgarcia360 hi David, could you please help review with this?

**Comment by dgarcia360** [comment]
Thanks @tchaikov! I've done the following:
- Merged https://github.com/dgarcia360/sphinx-multiversion/pull/4 
- sphinx-multiversion-scylla is tagged with a new release
- The new release of sphinx-multiversion-scylla is published to PyPi: https://pypi.org/project/sphinx-multiversion-scylla/#history
- There is no need to bump `sphinx-multiversion-scylla` in `docs/pyproject.toml`. The project should take the latest patch from PyPi automatically next time docs are published.

To trigger a new publication, could you please either:
- Re-run this workflow: https://github.com/scylladb/scylladb/actions/runs/4069477061 For more info, see [Re-running workflows and jobs](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs)
- or, merge a pull request that edits contents within the docs folder.

**Comment by tchaikov** [comment]
@dgarcia360 hi David, i don't have the privilege to rerun a workflow, neither can i merge a pull request to this project, as  i think we have a workflow to perform tests and promote/merge PRs which survive the tests.

probably we can just wait. if the next run is green. i will close this issue. what do you think?

**Comment by tchaikov** [comment]
still failing, see https://github.com/scylladb/scylladb/actions/workflows/docs-pages.yaml

**Comment by tchaikov** [comment]
see https://github.com/dgarcia360/sphinx-multiversion/pull/5

**Comment by dgarcia360** [comment]
@tchaikov In https://github.com/scylladb/scylladb/pull/12740, I'm calling "tags.add" after the builder is inited to make sure "tags" is defined.  I've tested it locally and should solve the error too.

In addition, I've released a new multiversion with https://github.com/dgarcia360/sphinx-multiversion/pull/5 in case there are other projects that try to call "tags" before the builder is inited.

**Comment by tchaikov** [comment]
@dgarcia360 David, thanks for fixing this! IIUC, either way should work -- after build is initialized or set this tags when loading the customized `conf.py`. as the tags are not dependent on builder i think.

anyway, let's see. will close this issue once the workflow passes.

**Comment by tchaikov** [comment]
closing. see https://github.com/scylladb/scylladb/actions/runs/4110084693/jobs/7092567155 for a green run.
