### PR TITLE
vector_search: fix decimal/varint precision loss in filter

### PR DESCRIPTION
**Pull request by m-szymon**
value_to_json() converts CQL values to JSON for vector search filters. For decimal and varint types, it used rjson::parse() on the JSON string, which parses through a double and silently loses precision for values exceeding ~15 significant digits — producing wrong filter results.

Additionally, for decimal type we need an exact string representation that preserves the original (unscaled, scale) pair, because partition keys use byte-level identity: different serialized representations of the same numeric value are distinct rows, so the filter must reproduce the exact representation stored in the key.

Add big_decimal::to_string_canonical() which follows the Java BigDecimal toString() spec (JDK 8+), producing a bijective string representation that uses exponential notation for extreme scales instead of expanding trailing zeros (which could cause OOM). This could replace to_string(), but doing so has wider consequences (e.g. hash/equality contract for decimal_type) described in SCYLLADB-1574. Use it in value_to_json() for decimal_type, and use rjson::from_string() for varint_type, both bypassing the lossy double parse path.

Tests cover the new to_string_canonical() and the filter fix, as well as existing decimal type behavior (key representation, clustering order, toJson) that we rely on and must not break. The CQL decimal type tests (test_type_decimal.py) also pass against Cassandra.

Fixes: https://scylladb.atlassian.net/browse/SCYLLADB-1583
Refs: https://scylladb.atlassian.net/browse/SCYLLADB-1574

Filtering was added in 2026.1 and this fix should be backported to enable full support of Decimal and Varint keys types.

### CODE REVIEW

**Comment by QuerthDP** [comment]
Finally some argument that we should've merged https://github.com/scylladb/scylladb/pull/28314 which gets rid of `rjson::parse`

File: vector_search/filter.cc [hunk 1]
```diff
@@ -59,6 +60,20 @@ rjson::value value_to_json(const data_type& type, const cql3::raw_value& val) {
...
+    // types (SCYLLADB-1574), revert its common use.
+    if (type == decimal_type) {
+        auto bd = value_cast<big_decimal>(type->deserialize(to_bytes(val.view())));
+        return rjson::from_string(bd.to_string_exact());
+    }
+    if (type == varint_type) {
+        auto json_str = to_json_string(*type, to_bytes(val.view()));
+        return rjson::from_string(json_str);
+    }
     auto json_str = to_json_string(*type, to_bytes(val.view()));
```
[the remark this answers is not in the document]
Comment (m-szymon) [reply vector_search/filter.cc]: Fixed.

File: utils/big_decimal.cc [hunk 2]
```diff
@@ -140,6 +140,72 @@ sstring big_decimal::to_string() const
...
+        if (_scale == 0) {
+            return "0";
+        }
+        int64_t adjusted_exp = static_cast<int64_t>(-_scale);
+        if (_scale >= 0 && adjusted_exp >= -6) {
+            std::string str = "0.";
+            str.append(_scale, '0');
+            return sstring(str);
+        }
+        return sstring("0E+") + std::to_string(-static_cast<int64_t>(_scale));
```
[the remark this answers is not in the document]
Comment (m-szymon) [reply utils/big_decimal.cc]: Fixed.

File: vector_search/filter.cc [hunk 3]
```diff
@@ -59,6 +60,20 @@ rjson::value value_to_json(const data_type& type, const cql3::raw_value& val) {
     if (val.is_null()) {
         return rjson::null_value();
     }
+    // For decimal and varint types, rjson::parse() on the JSON string would
+    // parse through a double, losing precision for large values. Instead,
+    // produce the numeric string directly and wrap it with rjson::from_string()
+    // which preserves the exact digits.
+    // TODO: once to_json_string() uses a lossless representation for these
+    // types (SCYLLADB-1574), revert its common use.
+    if (type == decimal_type) {
```
[the remark this answers is not in the document]
Comment (m-szymon) [reply vector_search/filter.cc]: I know.

**Review by m-szymon — COMMENTED** [review]
I fixed some small issues.
I confirmed with VS that it requires this fix to correctly handle varint/decimal keys (although patch to VS to introduce support is not yet finished).

I added test_type_varint.py with single test, which honestly I don't know how to interpret - a bug or a feature:
For varint it is also possible to send representation with prefix 0s, which is not re-normalized neither by Scylla nor Cassandra.
For partition keys it results in different partitions - but we can't represent it in JSON (which normalizes, but this one is not included in tests).
For clustering keys they are treated as the same value.

But this has consequences for VS implementation - does it have to normalize varint in any situation? 
This is similar to decimal, but for decimal it is clearly a "feature".
For varint it doesn't make much sense. Drivers (at least Python) normalize to minimal form and internal Scylla serialization does that as well - I couldn't create it in boost tests. Maybe with some raw bytes wrapping or blobToVarint machinery it would be possible.
My test does it with malicious monkey-patched driver.

**Comment by QuerthDP** [comment]
> Please replace this line with justification for the backport/* labels added to this PR

Missed this line in PR cover letter + add backport label

**Comment by QuerthDP** [comment]
Does this patch fix the SCYLLADB-1574? As I see the Jira automation did link this PR as a fix for that, although you mention this ticket only as reference

**Comment by m-szymon** [comment]
> Does this patch fix the [SCYLLADB-1574](https://scylladb.atlassian.net/browse/SCYLLADB-1574)? As I see the Jira automation did link this PR as a fix for that, although you mention this ticket only as reference

No, it doesn't fix it - it fixes sub-issue. I think that Jira shows linked PRs. I don't know how to tell it is going to close the issue. 1574 has status "in progress", while 1583 has status "in review", so I think this is correct.

> > Please replace this line with justification for the backport/* labels added to this PR
> 
> Missed this line in PR cover letter + add backport label

Actually I don't know if this should be backported and where. If it is not merged before current branch, then probably yes. But to earlier versions? In which version was it added?

[SCYLLADB-1574]: https://scylladb.atlassian.net/browse/SCYLLADB-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

File: test/boost/big_decimal_test.cc [hunk 4]
```diff
@@ -118,6 +119,132 @@ BOOST_AUTO_TEST_CASE(test_big_decimal_construct_from_string) {
     BOOST_REQUIRE_THROW(big_decimal("1.2E-2147483647"), marshal_exception);
 }
 
+// Test to_string_exact() against the Java BigDecimal.toString() specification.
+// Plain form is used iff scale >= 0 AND adjusted_exp >= -6
+// (where adjusted_exp = num_digits - 1 - scale).
+// Negative scales always produce exponential form.
```
Comment (nyh) [inline test/boost/big_decimal_test.cc:126]: How can you (or the reviewer like me) be sure that this really checks the behavior is the same as BigDecimal.toString()? Did you write a Java program? Where is it?

If you can find a CQL way to expose the to_string() operation - perhaps write a "decimal" number and then read it back? - then you can write a cqlpy test for it that you can run on Cassandra (with its Java BigDecimal) and Scylla and compare. It won't test to_string_exact(), but it it will show you how to_string() differs, and it will provide you the oracle (the correct values) for this test.

File: test/boost/big_decimal_test.cc [hunk 5]
```diff
@@ -118,6 +119,132 @@ BOOST_AUTO_TEST_CASE(test_big_decimal_construct_from_string) {
...
+
+    // Negative numbers
+    BOOST_REQUIRE_EQUAL(big_decimal("-45.6").to_string_exact(), "-45.6");
+    BOOST_REQUIRE_EQUAL(big_decimal("-1.23E+3").to_string_exact(), "-1.23E+3");
+    BOOST_REQUIRE_EQUAL(big_decimal("-1.23E-7").to_string_exact(), "-1.23E-7");
+
+    // DoS / OOM guard: extreme scales must not allocate unbounded memory.
+    // to_string() would previously expand trailing zeros in a loop;
+    // to_string_exact() uses exponential notation instead.
+    BOOST_REQUIRE_NO_THROW(big_decimal("1E+1000000000").to_string_exact()); // scale = -1e9
```
Comment (nyh) [inline test/boost/big_decimal_test.cc]: Why not check here that the result is equal 1E+1000000000, like you did in all other cases?

File: test/cqlpy/test_type_decimal.py [hunk 6]
```diff
@@ -128,3 +130,190 @@ def test_decimal_clustering_key_inline_overflow_exponent(cql, table1):
...
+    # Three representations of the numeric value 1230, each with a distinct
+    # (unscaled, scale) pair and therefore distinct wire bytes:
+    d1 = Decimal('1230')                   # as_tuple: (0, (1,2,3,0), 0)
+    d2 = Decimal('1.23E+3')               # as_tuple: (0, (1,2,3), 1)
+    d3 = Decimal((0, (1,2,3,0,0), -1))    # as_tuple: (0, (1,2,3,0,0), -1)
+    d_other = Decimal('456')
+    # Sanity: all three are numerically equal but have distinct as_tuple()
+    # (i.e., distinct (sign, digits, exponent) triples), meaning the CQL
+    # driver will serialize them to different wire bytes.
+    assert d1 == d2 == d3
```
Comment (nyh) [inline test/cqlpy/test_type_decimal.py:164]: Wow, I never knew that "d1 == d2 == d3" works in Python.
In all other languages I know it's either no allowed, or a bug trap.

File: test/cqlpy/test_type_decimal.py [hunk 7]
```diff
@@ -128,3 +130,190 @@ def test_decimal_clustering_key_inline_overflow_exponent(cql, table1):
...
+        stmt = cql.prepare(
+            f"INSERT INTO {table} (p, c, v) VALUES (?, ?, ?)")
+
+        # Insert 1: (p=d1, c=d1, v='a') — new row in partition d1.
+        cql.execute(stmt, [d1, d1, 'a'])
+        # Insert 2: (p=d1, c=d2, v='b') — same PK bytes as insert 1, same CK
+        # *value* but different CK representation → overwrites insert 1.
+        cql.execute(stmt, [d1, d2, 'b'])
+        # Insert 3: (p=d1, c=d_other, v='c') — same partition, different CK
+        # value → new row alongside the overwritten one.
```
Comment (nyh) [inline test/cqlpy/test_type_decimal.py]: Please try to avoid spurious unicode characters in the source code. I know Claude loves them, but ASCII goes a long way without needing special dashes, special arrows, etc.

File: test/cqlpy/test_type_decimal.py [hunk 8]
```diff
@@ -128,3 +130,190 @@ def test_decimal_clustering_key_inline_overflow_exponent(cql, table1):
...
+        # --- Partition d3: should be empty ---
+        # d3 is yet another representation of 1230 that was never used as a PK
+        # in any insert.  Because PK identity is byte-based, this is a distinct
+        # (and empty) partition.
+        rows_d3 = list(cql.execute(
+            cql.prepare(f"SELECT c, v FROM {table} WHERE p = ?"),
+            [d3]))
+        assert len(rows_d3) == 0
+
+        # --- Cross-representation CK lookup ---
```
Comment (nyh) [inline test/cqlpy/test_type_decimal.py:216]: Good. This is an important check. The above checks doing scans mostly focus on correctness of writes, and this one focuses on the correctness of read (how it looks up one clustering key).

File: utils/big_decimal.cc [hunk 9]
```diff
@@ -140,6 +140,59 @@ sstring big_decimal::to_string() const
...
+//   adjusted_exp = -scale + (precision - 1)
+//   if scale >= 0 AND adjusted_exp >= -6: plain decimal (no exponent)
+//   otherwise: exponential notation with 'E' suffix
+//
+// This guarantees a bijective mapping from (unscaled, scale) to string.
+// Using int64_t for adjusted_exp to avoid overflow when scale is extreme.
+//
+// This could replace to_string(), but doing so has wider consequences
+// (e.g. hash/equality contract for decimal_type) described in SCYLLADB-1574.
+sstring big_decimal::to_string_exact() const
```
Comment (nyh) [inline utils/big_decimal.cc]: The adjective "exact" sounds a bit ambiguous (and self-aggrandizing)  to me, but I don't know what better to suggest.

**Review by nyh — APPROVED** [review]

File: utils/big_decimal.cc (hunk 9 above)
Comment (m-szymon) [reply utils/big_decimal.cc]: to_string_canonical?

File: test/boost/big_decimal_test.cc (hunk 4 above)
Comment (m-szymon) [reply test/boost/big_decimal_test.cc:126]: Added link to specification and `test/cqlpy/test_type_decimal.py:test_decimal_tojson_representation`

**Review by QuerthDP — APPROVED** [review]
I've only reviewed the `filter.cc` and `filter_test.cc` parts.
Those look fine to me. I suppose the numerical changes were or are to be reviewed by @nyh already.
Nice work in finding and describing all the issues.

**Review by nyh — APPROVED** [review]

**Comment by nyh** [comment]
You were lucky, a merge freeze was declared by @dani-tweig five minutes after I merged your PR :-)

**Comment by yaronkaikov** [comment]
> You were lucky, a merge freeze was declared by @dani-tweig five minutes after I merged your PR :-)

I don't think he is so lucky, i think this patch is somehow breaking next build :-(, noticed it here - https://jenkins.scylladb.com/job/releng-testing/job/next/1221/
```
16:42:04  FAILED: [code=1] build/dev/test/vector_search/filter_test.o 
16:42:04  /usr/sbin/sccache /usr/local/sbin/clang++ -MD -MT build/dev/test/vector_search/filter_test.o -MF build/dev/test/vector_search/filter_test.o.d -std=gnu++23 -I/jenkins/workspace/releng-testing/next/scylla/seastar/include -I/jenkins/workspace/releng-testing/next/scylla/build/dev/seastar/gen/include -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=9 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=24 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DFMT_SHARED -I/usr/include/p11-kit-1 -g -ffile-prefix-map=/jenkins/workspace/releng-testing/next/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=westmere -DDEVEL -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -fpch-validate-input-files-content -O2 -DSCYLLA_BUILD_MODE=dev -iquote. -iquote build/dev/gen -std=gnu++23 -g -ffile-prefix-map=/jenkins/workspace/releng-testing/next/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=westmere -I/usr/include/p11-kit-1 -DBOOST_ALL_DYN_LINK    -fvisibility-inlines-hidden -Ikmipc/kmipc-2.1.0t-rhel84_64/include -DHAVE_KMIP -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/dev/test/vector_search/filter_test.o test/vector_search/filter_test.cc
16:42:04  test/vector_search/filter_test.cc:460:21: error: no matching function for call to 'get_restrictions_json'
16:42:04    460 |         auto json = get_restrictions_json(restr, false);
16:42:04        |                     ^~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:466:16: error: no matching function for call to 'get_restrictions_json'
16:42:04    466 |         json = get_restrictions_json(restr, false);
16:42:04        |                ^~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:471:53: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
16:42:04    471 |         auto filter = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
16:42:04        |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
16:42:04        |                                                                                  ^
16:42:04  test/vector_search/filter_test.cc:480:16: error: no matching function for call to 'get_restrictions_json'
16:42:04    480 |         json = get_restrictions_json(restr, false);
16:42:04        |                ^~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:487:54: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
16:42:04    487 |         auto filter2 = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
16:42:04        |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
16:42:04        |                                                                                  ^
16:42:04  test/vector_search/filter_test.cc:503:21: error: no matching function for call to 'get_restrictions_json'
16:42:04    503 |         auto json = get_restrictions_json(restr, false);
16:42:04        |                     ^~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  test/vector_search/filter_test.cc:508:53: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
16:42:04    508 |         auto filter = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
16:42:04        |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
16:42:04        |                                                                                  ^
16:42:04  7 errors generated.
```

**Comment by yaronkaikov** [comment]
> > You were lucky, a merge freeze was declared by @dani-tweig five minutes after I merged your PR :-)
> 
> I don't think he is so lucky, i think this patch is somehow breaking next build :-(, noticed it here - https://jenkins.scylladb.com/job/releng-testing/job/next/1221/
> 
> ```
> 16:42:04  FAILED: [code=1] build/dev/test/vector_search/filter_test.o 
> 16:42:04  /usr/sbin/sccache /usr/local/sbin/clang++ -MD -MT build/dev/test/vector_search/filter_test.o -MF build/dev/test/vector_search/filter_test.o.d -std=gnu++23 -I/jenkins/workspace/releng-testing/next/scylla/seastar/include -I/jenkins/workspace/releng-testing/next/scylla/build/dev/seastar/gen/include -Werror=unused-result -fstack-clash-protection -DSEASTAR_API_LEVEL=9 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=24 -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DFMT_SHARED -I/usr/include/p11-kit-1 -g -ffile-prefix-map=/jenkins/workspace/releng-testing/next/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=westmere -DDEVEL -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSCYLLA_ENABLE_ERROR_INJECTION -DSCYLLA_ENABLE_PREEMPTION_SOURCE -fpch-validate-input-files-content -O2 -DSCYLLA_BUILD_MODE=dev -iquote. -iquote build/dev/gen -std=gnu++23 -g -ffile-prefix-map=/jenkins/workspace/releng-testing/next/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=westmere -I/usr/include/p11-kit-1 -DBOOST_ALL_DYN_LINK    -fvisibility-inlines-hidden -Ikmipc/kmipc-2.1.0t-rhel84_64/include -DHAVE_KMIP -isystem abseil -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/dev/test/vector_search/filter_test.o test/vector_search/filter_test.cc
> 16:42:04  test/vector_search/filter_test.cc:460:21: error: no matching function for call to 'get_restrictions_json'
> 16:42:04    460 |         auto json = get_restrictions_json(restr, false);
> 16:42:04        |                     ^~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
> 16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
> 16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:466:16: error: no matching function for call to 'get_restrictions_json'
> 16:42:04    466 |         json = get_restrictions_json(restr, false);
> 16:42:04        |                ^~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
> 16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
> 16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:471:53: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
> 16:42:04    471 |         auto filter = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
> 16:42:04        |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
> 16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
> 16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
> 16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
> 16:42:04        |                                                                                  ^
> 16:42:04  test/vector_search/filter_test.cc:480:16: error: no matching function for call to 'get_restrictions_json'
> 16:42:04    480 |         json = get_restrictions_json(restr, false);
> 16:42:04        |                ^~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
> 16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
> 16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:487:54: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
> 16:42:04    487 |         auto filter2 = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
> 16:42:04        |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
> 16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
> 16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
> 16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
> 16:42:04        |                                                                                  ^
> 16:42:04  test/vector_search/filter_test.cc:503:21: error: no matching function for call to 'get_restrictions_json'
> 16:42:04    503 |         auto json = get_restrictions_json(restr, false);
> 16:42:04        |                     ^~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:57:9: note: candidate function not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const restrictions::statement_restrictions' for 1st argument
> 16:42:04     57 | sstring get_restrictions_json(const restrictions::statement_restrictions& restr, bool allow_filtering = false) {
> 16:42:04        |         ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  test/vector_search/filter_test.cc:508:53: error: no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'
> 16:42:04    508 |         auto filter = vector_search::prepare_filter(make_restrictions("pk=?", e), false);
> 16:42:04        |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./cql3/restrictions/statement_restrictions.hh:258:5: note: candidate constructor not viable: no known conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const statement_restrictions &' for 1st argument
> 16:42:04    258 |     statement_restrictions(const statement_restrictions&) = delete;
> 16:42:04        |     ^                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 16:42:04  ./vector_search/filter.hh:60:82: note: passing argument to parameter 'restrictions' here
> 16:42:04     60 | prepared_filter prepare_filter(const cql3::restrictions::statement_restrictions& restrictions, bool allow_filtering);
> 16:42:04        |                                                                                  ^
> 16:42:04  7 errors generated.
> ```

@m-szymon Please have a look

**Comment by avikivity** [comment]
Dequeued, breaks build

**Comment by yaronkaikov** [comment]
> Dequeued, breaks build

Thanks

**Comment by yaronkaikov** [comment]
This patch is breaking [next #10664](https://jenkins.scylladb.com/job/scylla-master/job/next/10664/):
- **Error:** `test/vector_search/filter_test.cc` fails to compile — `no matching function for call to 'get_restrictions_json'` and `no viable conversion from 'shared_ptr<const restrictions::statement_restrictions>' to 'const cql3::restrictions::statement_restrictions'`
- **Impact:** All 6 build stages fail (dev/debug/release on x86 and aarch64)

Offending commit: af3f3025bc — vector_search: fix decimal/varint precision loss in filter value_to_json()

**Regression analysis:** The new `to_json_decimal` and `to_json_varint` test cases call `get_restrictions_json(restr, false)` where `restr` is a `shared_ptr<const statement_restrictions>`. The function signature expects `const statement_restrictions&`. All existing tests correctly dereference with `*restr`. The same issue applies to the `prepare_filter` calls that pass `make_restrictions(...)` directly.

**Suggested fix:** Change all `get_restrictions_json(restr, false)` calls in the new test functions to `get_restrictions_json(*restr, false)` (dereference the shared_ptr). Similarly, verify `vector_search::prepare_filter(make_restrictions(...), false)` — `prepare_filter` likely expects a `const statement_restrictions&`, not a `shared_ptr`.

**Comment by m-szymon** [comment]
Because of this https://github.com/scylladb/scylladb/pull/29114
It needs rebase.

**Comment by yaronkaikov** [comment]
> #### :red_circle: CI State: FAILURE
> 
> | Mode | Stage | Status | Queue Time | Run Time | Node |
> |------|-------|--------|------------|----------|------|
> | | [Checkout](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28755//pipeline-overview) | :white_check_mark: |  | 2m | spider9.cloudius-systems.com |
> | | [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28755//pipeline-overview) | :x: |  | 1m | spider9.cloudius-systems.com |
> 
> #### Build Details:
> - Total Queue: 0m
> - Total Run: 3m
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

This CI failure is **not related to this PR's changes**. The "Framework test" stage failed due to an infrastructure issue: the LDAP server (`slapd`) failed to start during test environment setup.

| Stage | Verdict | Details |
|-------|---------|---------|
| Framework test | :construction: **Infrastructure issue** | `Exception: Unable to connect to slapd` — the test framework's LDAP service failed to start (`test/pylib/ldap_server.py:202`). This is a transient environment issue unrelated to the PR. No existing JIRA issue tracks this failure. Consider retriggering CI. |

**Comment by nyh** [comment]
This PR has two approvals and passing CI but we can't merge - merge freeze :-(
Remind me to come back when the merge freeze lifts...

**Comment by m-szymon** [comment]
> This PR has two approvals and passing CI but we can't merge - merge freeze :-( Remind me to come back when the merge freeze lifts...

@nyh I rebased to re-run CI. It is ready.

**Comment by m-szymon** [comment]
@scylladb/scylla-maint please consider merging.
