### ISSUE TITLE
CMake build regressed by commit 6517ca892000 ("service/qos/service_level_controller: Describe service levels", 2024-09-23)

### ISSUE THREAD

**Issue by lersek** [scylladb/scylladb#20821]
(@tchaikov FYI)

The commit noted in the title breaks the CMake-configured build.

Minimal reproducer, at commit da8047a834dc (but current master, i.e. ae764814441a, is also affected):

~~~
$ ./configure.py  --use-cmake

$ ninja -C build service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o

ninja: Entering directory `build'
[1/1] Building CXX object service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o
FAILED: service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o
/usr/bin/clang++ \
  -DDEBUG \
  -DDEBUG_LSA_SANITIZER \
  -DFMT_SHARED \
  -DSANITIZE \
  -DSCYLLA_BUILD_MODE=debug \
  -DSCYLLA_ENABLE_ERROR_INJECTION \
  -DSEASTAR_API_LEVEL=7 \
  -DSEASTAR_DEBUG \
  -DSEASTAR_DEBUG_PROMISE \
  -DSEASTAR_DEBUG_SHARED_PTR \
  -DSEASTAR_DEFAULT_ALLOCATOR \
  -DSEASTAR_LOGGER_COMPILE_TIME_FMT \
  -DSEASTAR_LOGGER_TYPE_STDOUT \
  -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 \
  -DSEASTAR_SHUFFLE_TASK_QUEUE \
  -DSEASTAR_SSTRING \
  -DSEASTAR_TYPE_ERASE_MORE \
  -DXXH_PRIVATE_API \
  -DCMAKE_INTDIR=\"Debug\" \
  -I$HOME/src/scylla \
  -I$HOME/src/scylla/build/gen \
  -I$HOME/src/scylla/seastar/include \
  -I$HOME/src/scylla/build/seastar/gen/include \
  -I$HOME/src/scylla/build/seastar/gen/src \
  -isystem $HOME/src/scylla/abseil \
  -g \
  -Og \
  -g \
  -gz \
  -std=gnu++23 \
  -fvisibility=hidden \
  -Wall \
  -Werror \
  -Wextra \
  -Wno-error=deprecated-declarations \
  -Wimplicit-fallthrough \
  -Wno-c++11-narrowing \
  -Wno-deprecated-copy \
  -Wno-mismatched-tags \
  -Wno-missing-field-initializers \
  -Wno-overloaded-virtual \
  -Wno-unsupported-friend \
  -Wno-enum-constexpr-conversion \
  -Wno-unused-parameter \
  -ffile-prefix-map=$HOME/src/scylla/build=. \
  -march=westmere \
  -Xclang \
  -fexperimental-assignment-tracking=disabled \
  -Werror=unused-result \
  -fstack-clash-protection \
  -fsanitize=address \
  -fsanitize=undefined \
  -fno-sanitize=vptr \
  -MD \
  -MT service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o \
  -MF service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o.d \
  -o service/CMakeFiles/service.dir/Debug/qos/service_level_controller.cc.o \
  -c $HOME/src/scylla/service/qos/service_level_controller.cc
In file included from $HOME/src/scylla/service/qos/service_level_controller.cc:9:
$HOME/src/scylla/cql3/util.hh:21:10: fatal error: 'cql3/CqlParser.hpp' file not found
   21 | #include "cql3/CqlParser.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
~~~

Bisection log:
~~~
git bisect start
# status: waiting for both good and bad commits
# bad: [da8047a834dc44051e14640bca8af656de9dd943] doc: add an intro to the Features page
git bisect bad da8047a834dc44051e14640bca8af656de9dd943
# status: waiting for good commit(s), bad commit known
# good: [61d19e4464c2d36dcebb7c50aec95fa863bfb207] Update tools/java submodule
git bisect good 61d19e4464c2d36dcebb7c50aec95fa863bfb207
# good: [d7945eea2a3f61e24eeb74ccaecdcbddca60a05b] docs/dev/service_levels: replace `unspecified` workload type with `NULL`
git bisect good d7945eea2a3f61e24eeb74ccaecdcbddca60a05b
# bad: [5e1d7f109aeaa18a2013885254764a51002f4910] docs/dev: Add documentation for DESC SCHEMA
git bisect bad 5e1d7f109aeaa18a2013885254764a51002f4910
# good: [86722e4ceab2bdd114700ca0cdf0653aee79c5ee] treewide: Return create statement optionally in describe functions
git bisect good 86722e4ceab2bdd114700ca0cdf0653aee79c5ee
# bad: [90ce86930a65d3928e901ada6e8e579ca7bc74c5] auth/authenticator: Add member functions for querying password hash
git bisect bad 90ce86930a65d3928e901ada6e8e579ca7bc74c5
# good: [7b4f9c806c900eb80003fb35509b54761ca5d887] treewide: Start using new overloads of describe
git bisect good 7b4f9c806c900eb80003fb35509b54761ca5d887
# bad: [6517ca89200017a1f90674cf8eb23e5e68d427ec] service/qos/service_level_controller: Describe service levels
git bisect bad 6517ca89200017a1f90674cf8eb23e5e68d427ec
# good: [b3573074061e1d4c945786fafa6f6ef89235d13c] data_dictionary: Remove keyspace_element.hh
git bisect good b3573074061e1d4c945786fafa6f6ef89235d13c
# first bad commit: [6517ca89200017a1f90674cf8eb23e5e68d427ec] service/qos/service_level_controller: Describe service levels
~~~

When not passing `--use-cmake` to `./configure`, there is no such symptom:

~~~
$ ./configure.py

$ ninja build/debug/service/qos/service_level_controller.o
[works fine]
~~~

I assume #20168 introduced some new deps on the ANTLR-generated files, and those new deps have not been added to `CMakeLists.txt`.

**Comment by dawmd** [comment]
Thank you, Laszlo, for looking into this. I'll investigate it as a priority.

**Comment by lersek** [comment]
@dawmd many thanks!

**Comment by tchaikov** [comment]
should be fixed by #20805

**Comment by tchaikov** [comment]
will close this issue once #20805 lands.

**Comment by lersek** [comment]
@tchaikov thanks for connecting the dots. I've asked @lkshminarayanan in #20805 to add `Fixes: #20805` to the PR blurb. That was, this one should be auto-closed, and more importantly, the merge commit message in the git history should capture a reference to this ticket as well.

**Comment by tchaikov** [comment]
> @tchaikov thanks for connecting the dots. I've asked @lkshminarayanan in #20805 to add `Fixes: #20821` to the PR blurb. That way, this one should be auto-closed, and more importantly, the merge commit message in the git history should capture a reference to this ticket as well.

@lersek hi Laszlo, unlike multi-commit pull request, we reuse the commit message of a single-commit pull request, in the merged commit. so, despite that adding the `Fixes` tag does help to connect the fix to the issue, the connection won't present in the git history.

**Comment by tchaikov** [comment]
on one hand, i want the change to be included sooner, on the other hand i try to respect the first come first serve policy, so i didn't request Lakshmi to update the commit message. i understand, in this perspective #20824 could be better.

**Comment by lersek** [comment]
right, I also thought about asking Lakshmi to rebase just to refresh the commit message -- but that would kick off CI again. :/
