### PR TITLE
view_update_generator: hold gate in process_staging_sstables

### PR DESCRIPTION
**Pull request by mlitvk**
Add a gate in view_update_generator and hold it in
process_staging_sstables. This function is called from the
view_building_worker and it can happen that it's called while the view
update generator is shutting down, so we use the gate to block new
requests when stopping the view update generator and to wait for
in-flight processing before the view update generator is destroyed.

Fixes [SCYLLADB-2073](https://scylladb.atlassian.net/browse/SCYLLADB-2073)

backport - fixes segfault during shutdown.

[SCYLLADB-2073]: https://scylladb.atlassian.net/browse/SCYLLADB-2073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: db/view/view_update_generator.cc [hunk 1]
```diff
@@ -237,33 +236,35 @@ std::pair<stop_iteration, uint64_t> view_update_generator::generate_updates_from
...
-        for(auto& sst: sstables) {
-            _progress_tracker->on_sstable_registration(sst);
-        }
+    auto holder = _gate.hold();
 
-        utils::get_local_injector().inject("view_update_generator_pause_before_processing",
-                utils::wait_for_message(std::chrono::minutes(5))).get();
+    for (auto& sst : sstables) {
+        _progress_tracker->on_sstable_registration(sst);
+    }
```
[the remark this answers is not in the document]
Comment (mlitvk) [reply db/view/view_update_generator.cc:244]: addressed this, although not directly related to the issue, thanks

File: db/view/view_update_generator.cc [hunk 2]
```diff
@@ -294,11 +295,16 @@ future<> view_update_generator::drain() {
...
     _db.unplug_view_update_generator();
+    auto gate_closed = _gate.close();
     do_abort();
-    return std::move(_started).then([this] {
-        _registration_sem.broken();
-    });
+    co_await std::move(_started);
+    _registration_sem.broken();
+    co_await std::move(gate_closed);
+    _progress_tracker = {};
```
Comment (Jadw1) [inline db/view/view_update_generator.cc]: Why we're moving `_progress_tracker = {};` from start to stop?

File: db/view/view_update_generator.cc [hunk 3]
```diff
@@ -294,11 +296,16 @@ future<> view_update_generator::drain() {
 }
 
 future<> view_update_generator::stop() {
+    if (_gate.is_closed()) {
+        co_return;
+    }
     _db.unplug_view_update_generator();
+    auto gate_closed = _gate.close();
```
Comment (Jadw1) [inline db/view/view_update_generator.cc]: Can't we just co_await _gate.close() here? The gate allows only running holders to finish, a new one won't be able to hold the gate.

Comment (mlitvk) [reply db/view/view_update_generator.cc]: yes, I suppose it's possible to just wait for the gate to close here.
I considered also adding the gate in `register_staging_sstable` and then it wouldn't work because it waits for the `_registration_sem` which is signaled by the vug loop.
eventually I thought there's no need for the gate there because it doesn't yield, it only waits for the sem at the end of the function.

File: db/view/view_update_generator.cc (hunk 2 above)
Comment (mlitvk) [reply db/view/view_update_generator.cc]: previously it was called in the abort/shutdown path after the loop is aborted.
I moved it, still in the shutdown path, but after the gate is closed, because we want to ensure there are no in-flight operations that access the progress tracker.

**Comment by piodul** [comment]
@Jadw1 please re-review and approve, if it is OK

**Review by Jadw1 — APPROVED** [review]
Looks good.

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued

**Comment by yaronkaikov** [comment]
> ## Build Failure in [next/11118](https://jenkins.scylladb.com/job/scylla-master/job/next/11118/)
> **All 6 build stages failed** (release/debug/dev on both x86_64 and aarch64) with compilation error:
> 
> ```
> ./db/view/view_update_generator.hh:81:19: error: duplicate member '_gate'
>    81 |     seastar::gate _gate;
>       |                   ^
> ./db/view/view_update_generator.hh:72:16: note: previous declaration is here
>    72 |     named_gate _gate{"view update generator"};
>       |                ^
> ```
> 
> **Root cause:** Merge conflict between this PR (#30092) and #30201. This PR adds `named_gate _gate{"view update generator"}` at line 72, while #30201 already added `seastar::gate _gate` at line 80. The merge commit `fd154a39` did not resolve the duplicate member.
> 
> **Offending commit:** `fd154a393` (merge by Piotr Dulikowski)
> 
> **Suggested fix:** Remove the older `seastar::gate _gate;` declaration (from #30201) and keep only the `named_gate _gate{"view update generator"}` from this PR, since it provides a descriptive name for the gate. Or consolidate both uses into a single gate member.

@scylladb/scylla-maint Can you please dequeue ?

**Comment by piodul** [comment]
> @scylladb/scylla-maint Can you please dequeue ?

@yaronkaikov done

**Comment by mlitvk** [comment]
The PR had real conflicts with @wmitros 's PR https://github.com/scylladb/scylladb/pull/30126 which also added a gate in the view update generator but for different users of the view update generator.
I changed the PR now to simply add a holder of the gate in `process_staging_sstables`, so now drain() will also abort and wait for process_staging_sstables, then stop() can abort and destroy the view update generator and _progress_tracker without racing with process_staging_sstables.
I also added the commit "view_update_generator: make drain/stop re-entrant", it was needed now to make the test work.
please review @wmitros

File: db/view/view_update_generator.cc [hunk 4]
```diff
@@ -242,6 +242,9 @@ future<> view_update_generator::process_staging_sstables(lw_shared_ptr<replica::
     for (auto& sst : sstables) {
         _progress_tracker->on_sstable_registration(sst);
     }
+    auto deregister_sstables = defer([this, sstables] {
```
Comment (wmitros) [inline db/view/view_update_generator.cc]: `sstables` is a vector of shared pointers so the copy shouldn't be that expensive but doesn't it make more sense to pass a reference here (`on_sstables_deregistration` takes a const reference)? Or instead we could keep the copy here and remove the copy below in `move_sstables_from_staging` by moving them

File: db/view/view_update_generator.cc [hunk 5]
```diff
@@ -237,6 +237,8 @@ std::pair<stop_iteration, uint64_t> view_update_generator::generate_updates_from
 }
 
 future<> view_update_generator::process_staging_sstables(lw_shared_ptr<replica::table> table, std::vector<sstables::shared_sstable> sstables) {
+    auto holder = _gate.hold();
```
Comment (wmitros) [inline db/view/view_update_generator.cc:240]: Does this error still reproduce without holding the gate here? This gate is also held for each view update, so we should be unable to generate new view updates even here if we're currently shutting down. Or maybe it's problematic if we process staging sstables only partially (holding the gate for the entire duration would help with that)?

Comment (mlitvk) [reply db/view/view_update_generator.cc:240]: the unit test reproduces the segmentation fault if I remove the gate. although, it could be that it's a scenario that happens only by the unit test and not in natural flows.
but I think it still solves an issue, because it protects the access to `_progress_tracker` in `process_staging_sstables` that is not protected by the gate of each view update.

File: db/view/view_update_generator.cc (hunk 4 above)
Comment (mlitvk) [reply db/view/view_update_generator.cc]: changed to pass by reference here, thanks

**Comment by mlitvk** [comment]
* rebase
* pass sstables vector by reference to deregister_sstables instead of by value

File: db/view/view_update_generator.cc (hunk 5 above)
Comment (wmitros) [reply db/view/view_update_generator.cc:240]: Ok, makes sense to keep it then

**Review by wmitros — APPROVED** [review]

**Review by piodul — APPROVED** [review]

**Comment by piodul** [comment]
Queued

**Comment by piodul** [comment]
@dani-tweig Looks like a backport was opened for this PR but Jira subtasks were not created

**Comment by dani-tweig** [comment]
> @dani-tweig Looks like a backport was opened for this PR but Jira subtasks were not created

@yaronkaikov , can you please check it out?

**Comment by yaronkaikov** [comment]
> > @dani-tweig Looks like a backport was opened for this PR but Jira subtasks were not created
> 
> @yaronkaikov , can you please check it out?

Ticket in JIRA please

**Comment by fruch** [comment]
@mlitvk seems like this one is missing for 2026.3

at least by https://scylladb.atlassian.net/browse/SCYLLADB-3415

**Comment by mlitvk** [comment]
> @mlitvk seems like this one is missing for 2026.3
> 
> at least by https://scylladb.atlassian.net/browse/SCYLLADB-3415

It looks like this PR did make it to 2026.3, but unfortunately the PR didn't resolve the issue completely

**Comment by fruch** [comment]
> > @mlitvk seems like this one is missing for 2026.3
> > 
> > at least by https://scylladb.atlassian.net/browse/SCYLLADB-3415
> 
> It looks like this PR did make it to 2026.3, but unfortunately the PR didn't resolve the issue completely

Already been spotted twice on 2026.3 branch, it's cause a crash, so it's almost always would be a blocker for the release.
