### PR TITLE
cql3: decouple statement_restrictions users from each other

### PR DESCRIPTION
**Pull request by avikivity**
statement_restrictions is the entry point for anything that has a WHERE clause:
SELECT, UPDATE, DELETE, CREATE MATERIALIZED VIEW AS SELECT, and even INSERT,
for which we generate a synthetic WHERE clause in order to unify the code path.

Each of these statement types accepts a different combination of restrictions, and each
wants something else from the analysis. The current state is to check everything and
return everything, with internal conditions on the statement type.

While reuse is good, too much is problematic. It is hard to change anything because
the analysis is constrained by many users. Error messages sometimes fit one statement
kind but not another. The code over-analyzes when simpler statements fall into the
code paths of the more complex statements.

Fix this by giving each statement type its own entry point and its own result, containing
only what it actually needs, and change the code path to only compute what it needs.

This prepares the way for additional refactoring, and improves a few error messages.

Refactoring, so not nominating for any backport.

### CODE REVIEW

File: cql3/statements/update_statement.cc [hunk 1]
```diff
@@ -95,268 +49,129 @@ update_statement::update_statement(
...
-{
-    auto stmt = ::make_shared<cql3::statements::update_statement>(audit_info(), statement_type::INSERT, ctx.bound_variables_size(), schema, std::move(attrs), stats);
-
-    // Created from an INSERT
-    if (stmt->is_counter()) {
-        throw exceptions::invalid_request_exception("INSERT statement are not allowed on counter tables, use UPDATE instead");
+void update_statement::process_where_clause(data_dictionary::database db, expr::expression where_clause, prepare_context& ctx) {
+    _restrictions = restrictions::analyze_update_restrictions(db, s, where_clause, ctx,
+            applies_only_to_static_columns());
+    classify_exists_condition(_restrictions->has_clustering_columns_restriction());
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/update_statement.cc:122]: _(Reply written by Claude, on Avi's behalf.)_

This is not a regression — master has the same ordering.

On master, `modification_statement::process_where_clause()` calls `analyze_statement_restrictions(db, s, type, where_clause, ctx, applies_only_to_static_columns(), ...)` and only classifies the `IF EXISTS` / `IF NOT EXISTS` condition afterwards. The "modifies only static columns" rejection lives inside that analysis (`statement_restrictions.cc`, `if (selects_only_static_columns && has_clustering_columns_restriction())`), so on master it, too, sees the pre-classification value of `applies_only_to_static_columns()`.

This series moves that check into `analyze_mutation()`, at the same point in the same sequence, reading the same value. `UPDATE t SET s = 3 WHERE k = 0 AND v = 1 IF EXISTS` is rejected before and after, which also matches Cassandra. The suggested fix would accept a statement that is rejected today, so it is a behaviour change rather than a fix, and out of scope here.

The comment does point at something real, though: `applies_only_to_static_columns()` is read at two points with a mutation of it in between, and only an argument — not the structure — keeps that correct. Splitting the mutation statements along the static-row / clustering-row axis would retire the flag entirely; that is noted as deferred follow-up work for this series.

File: cql3/statements/insert_statement.cc [hunk 2]
```diff
@@ -0,0 +1,428 @@
...
+{
+    // FIXME: handle _if_not_exists. For now, mark it used to quiet the compiler. #8682
+    (void)_if_not_exists;
+    throwing_assert(expr::is<cql3::expr::untyped_constant>(_json_value) || expr::is<cql3::expr::bind_variable>(_json_value));
+    auto json_column_placeholder = ::make_shared<column_identifier>("", true);
+    auto prepared_json_value = prepare_expression(_json_value, db, "", nullptr, make_lw_shared<column_specification>("", "", json_column_placeholder, utf8_type));
+    expr::verify_no_aggregate_functions(prepared_json_value, "JSON clause");
+    expr::fill_prepare_context(prepared_json_value, ctx);
+    auto stmt = ::make_shared<cql3::statements::insert_prepared_json_statement>(audit_info(), ctx.bound_variables_size(), schema, std::move(attrs), stats, std::move(prepared_json_value), _default_unset);
+    prepare_conditions(db, *schema, ctx, *stmt);
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/insert_statement.cc:423]: _(Reply written by Claude, on Avi's behalf.)_

Correct that JSON `INSERT ... IF NOT EXISTS` is not honoured, but that is pre-existing and deliberate, not something this series introduces. Master's `raw::insert_json_statement::prepare_internal()` ends the same way, with the comment it carries there:

```
// FIXME: handle _if_not_exists. For now, mark it used to quiet the compiler. #8682
(void)_if_not_exists;
```

The move to `insert_statement.cc` preserved that verbatim; scylladb/scylladb#8682 tracks it.

The suggested one-liner would not be the right fix either. Classifying the condition makes `has_conditions()` true, which routes the statement into the LWT path for the first time — a behaviour change that needs the rest of the conditional machinery (a CAS result set built from the JSON document's columns, among other things) and its own test coverage. Fixing #8682 is worth doing, but on its own, not folded into a refactoring series.

File: cql3/restrictions/where_clause_analysis.hh [hunk 3]
```diff
@@ -0,0 +1,295 @@
+/*
+ * Copyright (C) 2015-present ScyllaDB
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/restrictions/where_clause_analysis.hh]: _(Reply written by Claude, on Avi's behalf.)_

Fixed, and also in `cql3/statements/insert_statement.cc`, which is new too and was missed here. All three now say 2026-present, matching what new files in the repo use.

**Comment by avikivity** [comment]
v2: 
 - update copyright year on new files

File: cql3/statements/insert_statement.cc [hunk 4]
```diff
@@ -0,0 +1,428 @@
...
+    return ranges;
+}
+
+query::clustering_row_ranges insert_prepared_json_statement::create_clustering_ranges(const query_options& options, const json_cache_opt& json_cache) const {
+    query::clustering_row_ranges ranges;
+    std::vector<bytes_opt> exploded;
+    for (const auto& def : s->clustering_key_columns()) {
+        auto json_value = json_cache->find(def.name_as_text());
+        if (json_value == json_cache->end() || !json_value->second) {
+            throw exceptions::invalid_request_exception(format("Missing mandatory PRIMARY KEY part {}", def.name_as_text()));
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/insert_statement.cc:301]: _(Reply written by Claude, on Avi's behalf.)_

Both halves of this are real, and I confirmed them by experiment against this branch:

```
CREATE TABLE t (p int, c int, s int static, r int, PRIMARY KEY (p, c))
INSERT INTO t JSON '{"p": 1, "c": 2, "s": 7, "r": 8}'
SELECT p, c, s, r FROM t   ->  Row(p=1, c=2, s=None, r=8)      -- the static value is silently dropped

CREATE TABLE t2 (p int, c int, s int static, PRIMARY KEY (p, c))
INSERT INTO t2 JSON '{"p": 1, "s": 7}'
  ->  InvalidRequest: Missing mandatory PRIMARY KEY part c        -- static-row form rejected
```

But neither is introduced here. `insert_prepared_json_statement::maybe_prepare_json_cache()`, `build_partition_keys()`, `create_clustering_ranges()` and `execute_operations_for_key()` are byte-identical to the versions on master (they were `update_statement.cc`'s before this series moved them); the `regular_columns()` loop and the unconditional full-clustering-key requirement are both master's code, unchanged.

What the series does change is the surrounding asymmetry, which is why this is visible now: the non-JSON `insert_statement::create_clustering_ranges()` gained an explicit static-row / COMPACT-STORAGE-prefix case, so plain `INSERT` and `INSERT JSON` now sit side by side in one file and disagree. That makes the JSON limitation easier to see, not newer.

Fixing it means making the JSON path static-column-aware end to end — iterating `static_and_regular_columns()`, and deciding the clustering-key requirement from what the document actually sets — with tests for the silent-drop case, which nothing in `test/cqlpy` covers today. That is a behaviour fix and belongs in its own patch, not in a refactoring series that is meant to preserve behaviour exactly. Worth an issue of its own, alongside #8682.

**Comment by avikivity** [comment]
Filed ticket for pre-existing bugs:
 - https://scylladb.atlassian.net/browse/SCYLLADB-4465
 - https://scylladb.atlassian.net/browse/SCYLLADB-4466

**Comment by avikivity** [comment]
16m	spider4.cloudius-systems.com
> #### Failed Tests (1/10837):
> * [test/boost/schema_loader_test.cc::test_dropped_columns](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/33193/testReport/junit/boost.schema_loader_test/cc/test_dropped_columns_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%22test_dropped_columns.dev.1%22) [🎫](https://scylladb.atlassian.net/issues/?jql=text~%22test_dropped_columns%22) [📂](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/33193/artifact/testlog/x86_64/dev/failed_test/test_dropped_columns.dev.1/)
> 

Caused by the series - we introduced insert_statement, and the schema loader code tried to dynamic_cast into update_statement. Changed to dynamic_cast into modification_statement.

**Comment by avikivity** [comment]
v3:
 - change schema_loader to expect modification_statement rather than update_statement, since INSERTs are no longer mapped to update_statement.

File: tools/schema_loader.cc [hunk 5]
```diff
@@ -346,7 +346,7 @@ std::vector<schema_ptr> do_load_schemas(const db::config& cfg, std::string_view
             it->secondary_idx_man.reload();
             auto view = p->create_view_for_index(it->schema, index, db);
             real_db.tables.emplace_back(dd_impl, dd_impl.unwrap(ks), view, true);
-        } else if (auto p = dynamic_cast<cql3::statements::update_statement*>(statement)) {
+        } else if (auto p = dynamic_cast<cql3::statements::modification_statement*>(statement)) {
```
[the remark this answers is not in the document]
Comment (avikivity) [reply tools/schema_loader.cc]: This is correct but a pre-existing problem.

Filed https://scylladb.atlassian.net/browse/SCYLLADB-4467

**Comment by nyh** [comment]
> Filed ticket for pre-existing bugs:
> 
>     * https://scylladb.atlassian.net/browse/SCYLLADB-4465
> 
>     * https://scylladb.atlassian.net/browse/SCYLLADB-4466

Nice catches.
I hope you (or somebody else) remembers to work on these issues. With AI, fixing such bugs often takes less than an hour, including writing the regression tests.

**Comment by avikivity** [comment]
> > Filed ticket for pre-existing bugs:
> > ```
> > * https://scylladb.atlassian.net/browse/SCYLLADB-4465
> > 
> > * https://scylladb.atlassian.net/browse/SCYLLADB-4466
> > ```
> 
> Nice catches. I hope you (or somebody else) remembers to work on these issues. With AI, fixing such bugs often takes less than an hour, including writing the regression tests.

Well, that's why I filed tickets. They're indeed low hanging fruit.

File: cql3/statements/insert_statement.cc [hunk 6]
```diff
@@ -0,0 +1,428 @@
...
+
+        auto&& value = _column_values[i];
+
+        if (def->is_primary_key()) {
+            // Prepare the value against the column it is written to, exactly as
+            // the WHERE clause this used to synthesize did: that is what puts
+            // the bind marker in the prepare context under this column's name,
+            // which is what token-aware routing reads back.
+            auto prepared = expr::prepare_expression(value, db, schema->ks_name(), schema.get(),
+                    def->column_specification);
```
[the remark this answers is not in the document]
Comment (avikivity) [reply cql3/statements/insert_statement.cc:377]: Good catch, will add a regression test and fix.

File: tools/schema_loader.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (avikivity) [reply tools/schema_loader.cc]: Will fix, it's somewhat of a side path to merit a regression test (since we don't really expect DELETE statements here and this isn't user-visible).

**Comment by avikivity** [comment]
v4:
 - tightened check in schema recovery in tools/schema_loader.cc to exclude DELETE statements on dropped_columns
 - added regression test for rejecting aggregation functions in cql3 VALUES clause (works on Cassandra too)
 - fixed VALUES clause to reject aggregation functions (now referring to the VALUES clause rather than the nonexistent WHERE clause)

File: test/cqlpy/test_aggregate.py [hunk 7]
```diff
@@ -224,6 +224,18 @@ def test_reject_aggregates_in_where_clause(cql, table1):
     assert_invalid_message(cql, table1, 'Aggregation',
                            f'SELECT * FROM {table1} WHERE p = sum((int)4)')
 
+# An aggregate function has nothing to aggregate over in an INSERT, so the
+# statement must be rejected when it is prepared, rather than fail when the
+# aggregate is evaluated. This is as true of a primary-key column as it is of
+# a regular one.
+def test_reject_aggregates_in_insert(cql, table1):
+    assert_invalid_message(cql, table1, 'Aggregation',
```
Comment (nyh) [inline test/cqlpy/test_aggregate.py]: This test doesn't really test what it claims, that the prepare fails. It just checks the message, but the function it calls may actually run both prepare and execute if prepared succeeded!

The solution: don't use these stupid cassandra_tests.porting assertion functions, I'm sorry I didn't catch this when some introduced the first use into this file. You should use normal boto3 functions, where it will be clear that you call prepare(), not execute().

File: test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py [hunk 8]
```diff
@@ -1208,16 +1208,19 @@ def testInsertWithCompactStorageAndTwoClusteringColumns(cql, test_keyspace, forc
                    row(0, 0, 0, 0),
                    row(0, 0, 1, 1))
 
-        # Invalid Null values for the clustering key or the regular column
-        assertInvalidMessage(cql, table, "PRIMARY KEY column \"clustering_2\" cannot be restricted as preceding column \"clustering_1\" is not restricted",
+        # Invalid Null values for the clustering key or the regular column.
+        # An INSERT names the row it creates, so the clustering columns it names
+        # have to form a prefix of the clustering key; Scylla reports the first
+        # one left out, Cassandra lists them.
+        assertInvalidMessageRE(cql, table, 'Missing mandatory PRIMARY KEY part clustering_1|Some clustering keys are missing: clustering_1',
```
Comment (nyh) [inline test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py]: I don't understand, you changed the one original message - which worked on Cassandra too - to two **different** messages. Does this test still pass on Cassandra? Please check with `test/cqlpy/run-cassandra --dockert testfile.py::testname`.

File: test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py [hunk 9]
```diff
@@ -1208,16 +1208,19 @@ def testInsertWithCompactStorageAndTwoClusteringColumns(cql, test_keyspace, forc
...
                              "INSERT INTO %s (partitionKey, clustering_2, value) VALUES (0, 0, 0)")
         assertInvalidMessage(cql, table, "Column value is mandatory for this COMPACT STORAGE table",
                              "INSERT INTO %s (partitionKey, clustering_1, clustering_2) VALUES (0, 0, 0)")
 
         # Missing primary key columns
         assertInvalidMessage(cql, table, "partitionkey",
                              "INSERT INTO %s (clustering_1, clustering_2, value) VALUES (0, 0, 1)")
-        assertInvalidMessage(cql, table, "PRIMARY KEY column \"clustering_2\" cannot be restricted as preceding column \"clustering_1\" is not restricted",
+        assertInvalidMessageRE(cql, table, 'Missing mandatory PRIMARY KEY part clustering_1|Some clustering keys are missing: clustering_1',
```
Comment (nyh) [inline test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py]: Ditto. Please verify that this test still passes on Cassandra.

**Review by nyh — CHANGES_REQUESTED** [review]
Looks good, I'm just "requesting changes" because of a couple of problems I found in the tests.

I have to be honest, this patch included a huge amount of code, almost all of it was clearly just being moved around so I couldn't really review all the code that was being moved, so I focused on reading the commit messages and random pieces of the code that looked interesting, and I think everything checks out. I hope - and believe - that we have good regression tests for all the code changed in this patch, but a real working test-coverage tool would have been really helpful right about now.

File: test/cqlpy/test_aggregate.py (hunk 7 above)
Comment (avikivity) [reply test/cqlpy/test_aggregate.py]: Changed to test directly against prepare, and not use cassandrta_test.porting functions.

Filed https://scylladb.atlassian.net/browse/SCYLLADB-4489

File: test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py (hunk 8 above)
Comment (avikivity) [reply test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py]: Fixed and verified against Cassandra.

File: test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py (hunk 9 above)
Comment (avikivity) [reply test/cqlpy/cassandra_tests/validation/operations/compact_storage_test.py]: Fixed and verified against Cassandra.

**Comment by avikivity** [comment]
v5:
 - adjusted the test for rejecting aggregates in VALUES clause to test against prepare
 - adjusted tests to pass against Cassandra again
 - avoid cassandra_tests.porting facilities in original tests

**Comment by avikivity** [comment]
@nyh please review again, I have another, more interesting, batch piled on top

File: cql3/restrictions/statement_restrictions.cc [hunk 10]
```diff
@@ -1035,6 +1035,28 @@ void update_restrictions::analyze_update(
...
+    rows.reserve(ranges.size());
+    for (const auto& range : ranges) {
+        if (!range.start()) {
+            // No clustering restriction at all: the static row.
+            rows.push_back(clustering_key_prefix::make_empty());
+        } else if (range.is_singular()) {
+            rows.push_back(range.start()->value());
+        } else {
+            // analyze_update() rejects anything that would name a range of rows.
+            on_internal_error(rlogger, format("update_restrictions: not a single row: {}", range));
```
Comment (andrzej-jackowski-scylladb) [inline cql3/restrictions/statement_restrictions.cc:1050]: The following used to work before this patch series:
```
CREATE TABLE t (p int, c1 int, c2 int, v int, PRIMARY KEY (p, c1, c2))
    WITH CLUSTERING ORDER BY (c1 DESC, c2 DESC);
UPDATE t SET v = 1 WHERE p = 1 AND (c1, c2) = (1, 2);
```

Now it fails with an error message:
> NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.0.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="update_restrictions: not a single row: [ckp{000400000001000400000002},ckp{000400000001000400000002}] Backtrace:  ...

Comment (avikivity) [reply cql3/restrictions/statement_restrictions.cc:1050]: It is very bad that this was not caught by our unit tests.

How did you catch it? Code inspection?

Comment (nyh) [reply cql3/restrictions/statement_restrictions.cc:1050]: Sad. For the older CQL features, originally tested by dtest, writing and running tests was so painful that we tested only some bare minimum and certainly not every conceivable esoteric combination of parameters. Many of these esoteric combinations only come up during development while you're deep into the code - e.g., I believe @andrzej-jackowski-scylladb is now deep into debugging problems caused by "CLUSTERING ORDER .... DESC" which is how he thought of or noticed this new problem while writing tests for DESC.

I think that we should be very diligent in writing many new tests in test/cqlpy for every feature we develop or just change or even just look at. Writing tests in test/cqlpy was always very easy (Python is easy, no re-compilation and a roughly-one-second time to run a single test via test/cqlpy/run!) but has become even easier with AI. Nowadays AI checks for me whether a test for some scenario I thought of exists, and if not, I write a comment describing the scenario and let Claude write the test for me. Last week I wrote almost 200 tests this way (for the new Alternator vector search API, attempting to cover ever little and not-so-little detail).

Comment (nyh) [reply cql3/restrictions/statement_restrictions.cc:1050]: Please tell me when you add the missing test and fix the bug, and I'll review again.

Comment (avikivity) [reply cql3/restrictions/statement_restrictions.cc:1050]: I will sick Claude on removing reversed_type_impl.

Comment (andrzej-jackowski-scylladb) [reply cql3/restrictions/statement_restrictions.cc:1050]: > How did you catch it? Code inspection?

After skim reading all commits I asked claude code:
 `Review https://github.com/scylladb/scylladb/pull/31632, aren't any checks skipped or too many checks added somewhere?`

**Comment by avikivity** [comment]
v6:
 - add test for single-row UPDATE and DELETE in clustering row tuple form with all-reversed clustering keys
 - only reverse a clustering range for UPDATE/DELETE when all clustering keys are reversed if the range is not singular

**Review by nyh — APPROVED** [review]

File: test/cqlpy/test_aggregate.py [hunk 11]
```diff
@@ -224,6 +224,18 @@ def test_reject_aggregates_in_where_clause(cql, table1):
     assert_invalid_message(cql, table1, 'Aggregation',
                            f'SELECT * FROM {table1} WHERE p = sum((int)4)')
 
+# An aggregate function has nothing to aggregate over in an INSERT, so the
+# statement must be rejected when it is prepared, rather than fail when the
+# aggregate is evaluated. This is as true of a primary-key column as it is of
+# a regular one. We deliberately call prepare(), and not execute(), so that
+# the test can only pass if it is the preparation that fails.
```
[the remark this answers is not in the document]
Comment (avikivity) [reply test/cqlpy/test_aggregate.py:231]: It's a regression test against regressions introduced by this very series, so no ticket.

File: test/cqlpy/test_clustering_order.py [hunk 12]
```diff
@@ -65,3 +65,57 @@ def test_multi_column_relation_desc(cql, table2):
...
+    schema="p int, c1 int, c2 int, v int, PRIMARY KEY (p, c1, c2)"
+    order="WITH CLUSTERING ORDER BY (c1 DESC, c2 DESC)"
+    with new_test_table(cql, test_keyspace, schema, order) as table:
+        yield table
+
+# A multi-column equality names a single row, and UPDATE and DELETE are
+# allowed to use it. The bounds for a table whose clustering columns are
+# all descending are computed in the natural order and then reversed, and
+# the reversal used to turn the single row into a range of rows, which the
+# statements then refused to write.
```
[the remark this answers is not in the document]
Comment (avikivity) [reply test/cqlpy/test_clustering_order.py]: It's a regression introduced by previous versions of the series. Now it's there to prevent this series from regressing.

**Comment by avikivity** [comment]
v7:
 - minor comment edits to please the bots
 - dropped some unnecessary accessor

**Comment by avikivity** [comment]
CI was confused by quick pushes, maybe.

@scylladbbot trigger-ci

**Comment by avikivity** [comment]
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Queue Time	Run Time	Node
> [Checkout](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/33306//pipeline-overview)	✅		2m	spider9.cloudius-systems.com
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/33306//pipeline-overview)	✅		0m	spider9.cloudius-systems.com
> [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/33306//pipeline-overview)	❌	1h 28m	8m	spider17.cloudius-systems.com
> #### Build Failure:
> ```
> [2026-09-15T21:55:03.697Z] FAILED: [code=1] build/debug/cql3/statements/strong_consistency/modification_statement.o 
> [2026-09-15T21:55:03.697Z] /usr/sbin/sccache /usr/local/sbin/clang++ -MD -MT build/debug/cql3/statements/strong_consistency/modification_statement.o -MF build/debug/cql3/statements/strong_consistency/modification_statement.o.d -std=gnu++26 -I/jenkins/workspace/scylla-master/scylla-ci/scylla/fmt/include -I/jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include -I/jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/gen/include -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fsanitize=vptr -DSEASTAR_API_LEVEL=9 -DSEASTAR_BUILD_SHARED_LIBS -DSEASTAR_SSTRING -DSEASTAR_LOGGER_COMPILE_TIME_FMT -DSEASTAR_SCHEDULING_GROUPS_COUNT=25 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_HAVE_URING -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEBUG_PROMISE -DSEASTAR_LOGGER_TYPE_STDOUT -DSEASTAR_TYPE_ERASE_MORE -DBOOST_PROGRAM_OPTIONS_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DFMT_SHARED -I/usr/include/p11-kit-1 -g -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=x86-64-v3 -mpclmul -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -fpch-validate-input-files-content -Og -DSCYLLA_BUILD_MODE=debug -g -gz -iquote. -iquote build/debug/gen -std=gnu++26 -g -ffile-prefix-map=/jenkins/workspace/scylla-master/scylla-ci/scylla=. -DSEASTAR_NO_EXCEPTION_HACK -fextend-variable-liveness=none -march=x86-64-v3 -mpclmul -I/usr/include/p11-kit-1 -DBOOST_ALL_DYN_LINK    -fvisibility-inlines-hidden -Ikmipc/kmipc-2.1.0t-rhel84_64/include -DHAVE_KMIP -isystem abseil -isystem fmt/include -Wall -Werror -Wextra -Wimplicit-fallthrough -Wno-mismatched-tags -Wno-c++11-narrowing -Wno-overloaded-virtual -Wno-unused-parameter -Wno-unsupported-friend -Wno-missing-field-initializers -Wno-deprecated-copy -Wno-error=deprecated-declarations -Wno-error=pass-failed -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN  -c -o build/debug/cql3/statements/strong_consistency/modification_statement.o cql3/statements/strong_consistency/modification_statement.cc -Winvalid-pch -Xclang -include-pch -Xclang build/debug/stdafx.hh.pch
> [2026-09-15T21:55:03.699Z] cql3/statements/strong_consistency/modification_statement.cc:58:17: error: no member named 'restrictions' in 'cql3::statements::modification_statement'
> [2026-09-15T21:55:03.699Z]    58 |     _statement->restrictions().validate_primary_key(options);
> [2026-09-15T21:55:03.699Z]       |     ~~~~~~~~~~~~^
> [2026-09-15T21:55:03.699Z] 1 error generated.
> ```
> 
> #### Build Details:
> * Total Queue: 1h 28m
> * Total Run: 1h 39m
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

Conflict with newly merged https://github.com/scylladb/scylladb/commit/994064f6d6991dd2fc975393dbfbb6d134001bbc, needs rebase.

**Comment by avikivity** [comment]
v7:
 - rebase past logical conflict in https://github.com/scylladb/scylladb/commit/994064f6d6991dd2fc975393dbfbb6d134001bbc

**Comment by avikivity** [comment]
v8: fix another logical conflict (same cause as v7)

**Comment by avikivity** [comment]
v9: rebase past 22be3b3925634bfa6edb2eb909c96846fab7b068
