### PR TITLE
types: fix ambiguity in align_up call

### LINKED ISSUE #16746: ScyallDB doesn't compile with boost versions >= 1.79.0
ScyllaDB compilation fails with the following error when compiled with boost versions >= 1.79.0

```
/temp/scylladb/types/types.cc:2581:16: error: no matching function for call to 'align_up'
        return align_up(boost::multiprecision::msb(num) + 2, 8u) / 8;
               ^~~~~~~~
/temp/scylladb/seastar/include/seastar/core/align.hh:36:3: note: candidate template ignored: deduced conflicting types for parameter 'T' ('typename std::enable_if<number_category<cpp_int_backend<0, 0, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, allocator<unsigned long long>>>::value == number_kind_integer, std::size_t>::type' (aka 'unsigned long') vs. 'unsigned int')
T align_up(T v, T align) {
  ^
/temp/scylladb/seastar/include/seastar/core/align.hh:42:4: note: candidate template ignored: could not match 'T *' against 'typename std::enable_if<number_category<cpp_int_backend<0, 0, boost::multiprecision::signed_magnitude, boost::multiprecision::unchecked, allocator<unsigned long long>>>::value == number_kind_integer, std::size_t>::type' (aka 'unsigned long')
T* align_up(T* v, size_t align) {
   ^
1 error generated.
ninja: build stopped: subcommand failed.

```

### PR DESCRIPTION
**Pull request by lkshminarayanan**
Compilation fails with recent boost versions (>=1.79.0) due to an ambiguity with the align_up function call. Fix that by adding type inference to the function call.

Fixes #16746

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]
lgtm.

**Comment by tchaikov** [comment]
BTW, this should address one of the FTBFS on f39.

**Review by denesb — APPROVED** [review]
