### ISSUE TITLE
test.py: AttributeError: 'builtin_function_or_method' object has no attribute 'add_signal_handler'

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#16623]
./test.py is broken. seen on master gating https://jenkins.scylladb.com/job/scylla-master/job/next/7023/ and 7024

@tchaikov probably caused by  https://github.com/scylladb/scylladb/commit/1c6c6952cab0a2d2cd035fa0b52cd13fb31d68f9 please take a look

```
12:11:54  + bash -c set -o pipefail; ./tools/toolchain/dbuild -v `pwd`:/scylladir -- ./test.py --tmpdir=/scylladir/testlog/aarch64 --verbose --repeat 1  2>&1 | tee output_test_aarch64.txt
12:12:25  Found 9004 tests.
12:12:25  Traceback (most recent call last):
12:12:25    File "/jenkins/workspace/scylla-master/next/scylla/./test.py", line 1615, in workaround_python26789
12:12:25      code = await main()
12:12:25             ^^^^^^^^^^^^
12:12:25    File "/jenkins/workspace/scylla-master/next/scylla/./test.py", line 1579, in main
12:12:25      setup_signal_handlers(asyncio.get_running_loop, signaled)
12:12:25    File "/jenkins/workspace/scylla-master/next/scylla/./test.py", line 1177, in setup_signal_handlers
12:12:25      loop.add_signal_handler(signo, lambda: asyncio.create_task(shutdown(loop, signo, signaled)))
12:12:25      ^^^^^^^^^^^^^^^^^^^^^^^
12:12:25  AttributeError: 'builtin_function_or_method' object has no attribute 'add_signal_handler'
```

**Comment by tchaikov** [comment]
@benipeled thank you! just ping'ed @denesb to remove the offending PR from next.

**Comment by tchaikov** [comment]
dequeued. so closing.
